/**
 * Emergency Contacts Type Definitions
 * Mirrors the BundleRecommendation pattern for consistency
 */

export type ContactType = 'personal' | 'professional' | 'agency' | 'community';

export type ContactCategory =
  | 'medical'
  | 'government'
  | 'family'
  | 'community'
  | 'utility'
  | 'information';

export type ContactPriority = 'critical' | 'important' | 'helpful';

export type ContactSource = 'static' | 'ai' | 'google_places' | 'user_added';

export type ContactRegion = 'local' | 'state' | 'national';

/**
 * Emergency Contact Recommendation
 * Generated by AI analysis combining static data and Google Places results
 */
export interface EmergencyContactRecommendation {
  id: string;
  name: string;
  type: ContactType;
  category: ContactCategory;
  phone: string;
  website?: string;
  email?: string;
  address?: string;

  // AI analysis fields (mirrors BundleRecommendation pattern)
  reasoning: string;
  relevantScenarios: string[];
  priority: ContactPriority;
  fitScore: number; // 0-100

  // Metadata
  region?: ContactRegion;
  availability24hr?: boolean;
  source: ContactSource;
  placeId?: string; // Google Places ID
  location?: { lat: number; lng: number };
  openingHours?: string;
}

/**
 * Meeting Location Recommendation
 * AI-suggested safe meeting points for family reunification
 */
export interface MeetingLocationRecommendation {
  id: string;
  name: string;
  address: string;
  description: string;
  placeId: string; // Google Places ID
  location: { lat: number; lng: number };
  placeType: string;
  reasoning: string;
  scenarioSuitability: string[]; // Which scenarios this location works for
  priority: 'primary' | 'secondary' | 'tertiary';
  isPublic: boolean;
  hasParking: boolean;
  isAccessible: boolean; // ADA accessible
  distanceFromHome?: number; // meters
  estimatedTravelTime?: string; // e.g., "15 minutes"
}

/**
 * Complete Emergency Contacts Section
 * Stored in ReportDataV2.sections.emergencyContacts
 */
export interface EmergencyContactsSection {
  contacts: EmergencyContactRecommendation[];
  meetingLocations: MeetingLocationRecommendation[];
  generatedAt: string; // ISO timestamp
  locationContext: string; // e.g., "Austin, TX"
  googlePlacesUsed: boolean; // Whether Google Places API was used
  aiAnalysisUsed: boolean; // Whether AI analysis was performed
}

/**
 * Google Places API Result Type
 * Response from NearbySearch API
 */
export interface GooglePlaceResult {
  placeId: string;
  name: string;
  types: string[];
  address: string;
  phone?: string;
  location: { lat: number; lng: number };
  openNow?: boolean;
  rating?: number;
  userRatingsTotal?: number;
  photos?: Array<{
    photoReference: string;
    width: number;
    height: number;
  }>;
}

/**
 * Static Contact Definition
 * Hardcoded universal emergency contacts (911, poison control, etc.)
 */
export interface StaticContact {
  id: string;
  name: string;
  type: ContactType;
  category: ContactCategory;
  phone: string;
  website?: string;
  email?: string;
  description: string;
  availability24hr: boolean;
  region: ContactRegion;
  applicableCountries: string[]; // ISO country codes
  applicableStates?: string[]; // US state codes
  relevantScenarios: string[];
  priority: ContactPriority;
  fitScore: number;
}
